############################################################
#
# Server \u670D\u52A1\u7AEF\u76F8\u5173\u914D\u7F6E
#
############################################################
# \u914D\u7F6Eapi\u7AEF\u53E3\u53F7
server:
  port: 8081
  # tomcat\u7684URI\u7F16\u7801
  tomcat:
    uri-encoding: utf-8

spring:
  ############################################################
  #
  # REDIS \u914D\u7F6E
  #
  ############################################################
  redis:
    # Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
    database: 1
    # Redis\u670D\u52A1\u5668\u5730\u5740
    host: 192.168.110.128
    # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
    port: 6379
    # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
#    password: 123456
    # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
    timeout: 200ms
    jedis:
      # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
      pool.max-active: 1000
      # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
      pool.max-wait: -1ms
      # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
      pool.max-idle: 10
      # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
      pool.min-idle: 2
  ############################################################
  #
  # \u914D\u7F6E\u6570\u636E\u6E90\u76F8\u5173	\u4F7F\u7528\u963F\u91CC\u5DF4\u5DF4\u7684 druid \u6570\u636E\u6E90
  #
  ############################################################
  datasource:
    url: jdbc:mysql://localhost:3306/video-dev?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  # \u6587\u4EF6\u4E0A\u4F20\u914D\u7F6E
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

############################################################
#
# mybatis \u914D\u7F6E
#
############################################################
# mybatis \u914D\u7F6E
mybatis:
  type-aliases-package: com.zing.boot.video.pojo
  mapper-locations: classpath:mapper/*.xml
# \u901A\u7528 Mapper \u914D\u7F6E
mapper:
  mappers: com.zing.boot.video.utils.MyMapper
  not-empty: false
  identity: MYSQL
# \u5206\u9875\u63D2\u4EF6\u914D\u7F6E
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql