server:
  port: 8000
spring:
  application:
    name: merchants
  datasource:
    url: jdbc:mysql:///passbook?autoReconnect=true&useSSL=true
    username: root
    password: 123456
  kafka:
    bootstrap-servers: 192.168.0.84:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
logging:
  level: debug
  file: merchants.log