server:
  port: 9000
spring:
  application:
    name: passbook
  datasource:
    url: jdbc:mysql:///passbook?autoReconnect=true&useSSL=true
    username: root
    password: 123456
  kafka:
    bootstrap-servers: 10.131.13.84:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 10.131.13.84:2181
      rootDir: file:///D:/tmp/root_dir
      nodeParent: /hbase
  redis:
    host: 10.131.13.84
    port: 6379
logging:
  level: debug
  file: passbook.log
